// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKvf8e7E7yXVq_z_u_3R6UH0qplpnpPxo',
    appId: '1:181744374672:web:01b9a4900b8c11a67d5915',
    messagingSenderId: '181744374672',
    projectId: 'lws-e-commerce',
    authDomain: 'lws-e-commerce.firebaseapp.com',
    storageBucket: 'lws-e-commerce.appspot.com',
    measurementId: 'G-Q4GW3KD5N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfeDALY4AJ2RXiWDueI_jTnTDLaaXweSE',
    appId: '1:181744374672:android:79fc1beb51b1aa0d7d5915',
    messagingSenderId: '181744374672',
    projectId: 'lws-e-commerce',
    storageBucket: 'lws-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZV656f7MXtK-8VKhQALH01Sl-L8NxSIk',
    appId: '1:181744374672:ios:5ee2b52a5b86a1927d5915',
    messagingSenderId: '181744374672',
    projectId: 'lws-e-commerce',
    storageBucket: 'lws-e-commerce.appspot.com',
    iosBundleId: 'com.lws.ecommerce',
  );
}
